### ISSUE TITLE
Download release

### ISSUE THREAD

**Issue by armando-basile** [xipki/ipkcs11wrapper#2]
Hi Xipki,
i try to download release but i can not find it on Github or on Maven with ipkcs11wrapper name.

How can i download ? 

Thanks

**Comment by xipki** [comment]
Just released the first version v1.0.1. It should be available under https://repo.maven.apache.org/maven2/org/xipki/ipkcs11wrapper/1.0.1/.

**Comment by armando-basile** [comment]
ok, i found it, could you explain steps to migrate from your sunpkcs11-wrapper to ipkcs11wrapper  ?

Thanks

**Comment by xipki** [comment]
ipkcs11wrapper is totally different. You may follow the examples under https://github.com/xipki/ipkcs11wrapper/tree/main/src/test/java/test/pkcs11/wrapper.

**Comment by armando-basile** [comment]
ok, i moving to ipkcs11wrapper, 2 questions:

1. In previous implementation i can execute getSetAttributes to have all attributes content from an object, how can i get it with ipkcs11wrapper 

2. In previous implementation i can not perform a finalize and a new initialize module, i need to stop and restart application. In ipkcs11wrapper is possible ?

Thanks

**Comment by xipki** [comment]
1. This is much simpler than in xipki/pkcs11wrapper, you specify exactly which attributes to read in the Session.getAttrValues() method, see https://github.com/xipki/ipkcs11wrapper/blob/main/src/test/java/test/pkcs11/wrapper/TestBase.java#L257 for example.

2. Yes, you can finalize a module by calling module.finalize(null). No re-start is needed.

**Comment by xipki** [comment]
Just released 1.0.2. Please use this version.

**Comment by armando-basile** [comment]
I terminated porting using 1.0.1 and seems work fine :) now i upgrade to 1.0.2

**Comment by xipki** [comment]
Sounds great. For the short messages, the *Single-methods are preferred. E.g. using encryptSingle() instead first encryptInit() then encrypt().

**Comment by xipki** [comment]
Just released v1.0.3. In most cases the new introduced PKCS11Token shall satisfy the requirements and is preferred. The application does need to manage the sessions.
