### ISSUE TITLE
ipkcs11wrapper & GraalVM native build

### ISSUE THREAD

**Issue by Anton-Bondar** [xipki/ipkcs11wrapper#3]
Hi ! Can I use ipkcs11wrapper library with GraalVM ? Maybe some example available. Because I don't understand which JNI classes should be specify in jniconfig.json.

**Comment by xipki** [comment]
1. No `jniconfig.json`is needed in ipkcs11wrapper.
2. Examples are available in https://github.com/xipki/ipkcs11wrapper/tree/main/src/test/java/test/pkcs11/wrapper.

**Comment by xipki** [comment]
I close this issued due to the inactivity. Re-open it if needed.
