### ISSUE TITLE
Sometimes arrives CKR_0X80000384 errors

### ISSUE THREAD

**Issue by armando-basile** [xipki/ipkcs11wrapper#6]
Hi xipki,
i'm trying to understand the reason of this error. I use a multithread application that implement this pattern:

1. Initialize Module (static and synchronized from only main thread)
2. Get list of slot (static and synchronized from only main thread)
3. Initialize Token (static and synchronized from only main thread)
4. Create Session (static and synchronized multi threading)
5. Perform activities (multi threading)
6. Close Session (multi threading)

It work fine but sometimes i receive this error and all activities on all static initialized tokens (create sessions, encrypt, signature, etc.) failed with CKR_0X80000384.
The only way to use the application is restart the application (so it close also Module communication)

I don't know if this pattern is correct or i should not use static tokens, but 
```
pkcs11_slots[slotReference].getToken();
```
before each create session

What do you think about ?

**Comment by xipki** [comment]
Please refer to https://github.com/xipki/jpkcs11wrapper/issues/3.

**Comment by xipki** [comment]
Close due to inactivity.
