### ISSUE TITLE
How to generate CSR

### ISSUE THREAD

**Issue by MrWildanMD** [xipki/ipkcs11wrapper#7]
Can i generate CSR with this library? if yes how can i do it?

**Comment by xipki** [comment]
The ipkcs11wrapper is just a wrapper of PKCS#11 interface. you need to build your own application to build the CSR, and call ipkcs11wrapper to sign the CSR.

**Comment by MrWildanMD** [comment]
alright i just considering way to do it...thanks for answer
if someone wondering too and found this, what you can do is:
- Export the private key
- Generate CSR using openssl/openssl bridge
- Sign the CSR
